name: Build APK with Custom AAPT2

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Download aapt2 artifact
        uses: actions/download-artifact@v4
        with:
          name: aapt2-binary
          path: custom-aapt2

      - name: Make aapt2 executable and override build-tools
        run: |
          mkdir -p $HOME/android-sdk/build-tools/33.0.1
          cp custom-aapt2/aapt2 $HOME/android-sdk/build-tools/33.0.1/aapt2
          chmod +x $HOME/android-sdk/build-tools/33.0.1/aapt2
          echo "✅ aapt2 injected into build-tools"

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug | tee build.log

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Send APK to Telegram
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: app/build/outputs/apk/debug/app-debug.apk
          message: "✅ APK built successfully."

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ failure() }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Send log to Telegram on failure
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ APK build failed.
            Check logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
