name: Build Android Build Tools for aarch64

on:
  workflow_dispatch:
  push:

jobs:
  build-aarch64-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y zip unzip build-essential curl

      - name: Clone Android Build Tools
        run: |
          git clone --depth=1 https://android.googlesource.com/platform/build tools && \
          cd tools && \
          ./gradlew :aapt2:assembleRelease

      - name: Find & zip aarch64 binaries
        run: |
          mkdir -p out
          find tools -type f -name 'aapt2' -exec cp {} out/aapt2 \;
          find tools -type f -name 'zipalign' -exec cp {} out/zipalign \;
          find tools -type f -name 'apksigner' -exec cp {} out/apksigner \;
          cd out && zip -r build-tools-aarch64.zip .

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: build-tools-aarch64
          path: out/build-tools-aarch64.zip

      - name: Print success message
        run: echo "✅ Native aarch64 build tools compiled and uploaded."

      - name: Telegram Notify (optional)
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Build tools for aarch64 ready.
            Download: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
