name: Build and Notify via Telegram

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: |
          ./gradlew assembleDebug --stacktrace --info > build.log 2>&1 || true
          if grep -q "BUILD SUCCESSFUL" build.log; then
            curl -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}"                  -F document=@app/build/outputs/apk/debug/app-debug.apk                  "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument"
          else
            tail -n 100 build.log > err.txt
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"                  -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}"                  --data-urlencode "text=❌ Build failed for `${{ github.repository }}`\nCommit: `${{ github.sha }}`\n```\n$(tail -n 30 build.log | head -c 3500)\n```"
          fi
