name: Build and Notify via Telegram

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build APK
        run: |
          ./gradlew assembleDebug --stacktrace --info > build.log 2>&1 || true
          if grep -q "BUILD SUCCESSFUL" build.log; then
            curl -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
                 -F document=@app/build/outputs/apk/debug/app-debug.apk \
                 "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument"
          else
            tail -n 80 build.log > err.txt
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
                 -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
                 --data-urlencode "text=❌ Build failed for \`${{ github.repository }}\`%0ACommit: ${{ github.sha }}%0A\n$(tail -n 30 build.log | sed 's/$/%0A/' | head -c 3500)"
          fi
