name: Notify on Build Failure

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Send Telegram message on failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ Build failed for `${{ github.repository }}`
            Commit: ${{ github.sha }}
            Error: ${{ steps.build.outcome }}
            Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
